### ISSUE TITLE
Start folder selection in the specified directory

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [ATrefzer/UmdhGui#2]
I wish the folder selection dialog in the settings would start at the specified directory.

Steps to reproduce:

1. Set tool directory using the folder selection, choose a 64 bit WinDbg
2. Set output directory using the folder selection
3. Try to change the tool directory to 32 Bit WinDbg. It will start in the output directory.

Expected behavior: the dialog starts in the 64 bit WinDbg directory (which is the current value of the tool directory)

**Comment by ATrefzer** [comment]
If the directory is valid it is the starting directory for the folder dialog now
