### ISSUE TITLE
Settings dialog may become unusable when it resizes

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [ATrefzer/UmdhGui#3]
The settings dialog automatically increases its size when entering a long symbol path.
Unfortunately, in a particular situation, my symbol path is 696 characters long and the dialog becomes 4138 pixels wide, so it spans 3 monitors.
Maybe there could be a maximum width of that dialog.

Or it could be similar to Visual Studio and provide one symbol location per line.
![grafik](https://user-images.githubusercontent.com/25632350/162766218-85f19bf7-d1d4-4a07-9fd3-eee0016d72da.png)

**Comment by ATrefzer** [comment]
Symbol Path TextBox is now multi line with an optional vertical scrollbar. The whole settings window has max sizes.
