### ISSUE TITLE
Vertical split instead of horizontal split

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [ATrefzer/UmdhGui#4]
My monitors are all horizontally oriented. That way I have plenty of space on the horizontal axis.
Both, the backtrace list and the callstack are long in a vertical manner.
As you can see in the following screenshot, a lot of space is wasted:

![grafik](https://user-images.githubusercontent.com/25632350/162777669-bf9ef2ab-1e90-4c21-b85e-ca53908e0b74.png)

Suggestion: split the screen vertically to make better use of the available screen space.

**Comment by ATrefzer** [comment]
You can click the Horizontal layout toggle button

![image](https://user-images.githubusercontent.com/36333177/172202396-32c60acf-0efa-45f4-a1cc-96d246bd52ea.png)
