### ISSUE TITLE
Allow inverted filters

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [ATrefzer/UmdhGui#5]
UmdhGui currently has a filter for "Stack contains". A filter for "Stack does not contain" would also be helpful.
Here's the use case: I have a mixed C++ / .NET application and I want to eliminate the `clr!operator new` leaks, since I suspect they are subject to garbage collection.

**Comment by ATrefzer** [comment]
Filters can be separated by ;
You can invert a filter expression with -- prefix now.
From the inclusive filters at least one has to occur in the callstack.
From the exclusive filters none must occur in the callstack.
Tooltip has a short hint.
