### ISSUE TITLE
Negative allocations are displayed incorrectly

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [ATrefzer/UmdhGui#7]
In my `.diff` file, the last allocation is

```
-    3540 ( 147956 - 151496)    283 allocs	BackTrace0
-       7 (    283 -    290)	BackTrace0	allocations

Total decrease ==   2614 requested +   -278 overhead =   2336
```

but it is displayed as positive in UMDHGui.

![grafik](https://user-images.githubusercontent.com/25632350/168563305-6a08d506-50ff-4bca-a0c7-4da29fe2615c.png)

**Comment by ATrefzer** [comment]
I only looked at the old bytes vs. new bytes when using the tool. 
The delta columns are now signed values to makes the output more readable.
